import { EMBED_VERSION } from '../embed'

/**
 * 顔の見本を、最初から持たせておく。
 *
 * **新しい端末は見本 0 枚から始まる。** そこがいちばん当たらない領域だと実測で
 * 分かっている（ことね 24 枚 → 96%、見本 4 枚の人 → 0〜75%）。1 枚目から
 * 提案が出るように、実機のスクショから採った見本を配る。
 *
 * 入っているのは **1 顔あたり 54 個の数だけ**で、絵は入っていない。
 * 0〜1 を 1 バイトに丸めて base64 にしてある ── 小数のままだと gzip 9.8KB、
 * 丸めると 3.5KB。丸めても当たり方は変わらない（実測で 89.6% のまま、
 * 外れの最高確信 0.275 → 0.279）。
 *
 * **名前で持つ。id では持てない。** 名簿の id は端末ごとに振られるので、
 * 配る側が知りようがない。読むときに名簿から引き当てる（lib/suggest.ts）。
 *
 * 名前は「話者として読めた綴り」と「話者チップの色」の 2 通りで引き、
 * 両方が出た所はすべて一致したものだけを使っている。
 */

/** この見本がどの版の記述子で採られたか。合わなければ丸ごと使わない。 */
export const SEED_EMBED_VERSION = 2

export interface SeedFace {
  readonly name: string
  /** 54 バイトを base64 にしたもの。1 バイト = 1 次元、0..255 が 0..1 */
  readonly embeds: readonly string[]
}

/** 版が合っていなければ空。古い見本を混ぜると距離が嘘になる。 */
export const seedFaces: readonly SeedFace[] =
  SEED_EMBED_VERSION !== EMBED_VERSION
    ? []
    : [
    {
      name: 'ことね',
      embeds: [
        'EEQAAAAAAAAAAAAAAAAAABCQJBsAAAAAAAAAAAAAAAAFCByKJykBAAAAAQAAAAAAAAEGCSFx',
        'DEUAAAAAAAAAAAAAAAAAABSHJBkAAAAAAAAAAAABAAEHEBl+LR8AAAAAAAAAAAAAAAAABBGM',
        'FSYBAAAAAAAAAAAAAAAGWGkXGg8AAAAAAwAAAAADAAQRUoICGBMBAQACBgAAAAACAA4mP28B',
        'IRwAAAAAAQAAAAAAAAAdUkMWFAEAAAAABAAAAAAEAAIONqIAFg8AAAAACAAAAAACAAgVNoEB',
        'DSoBAAAAAAAAAAAAAAAIOYkEFBUAAAAAAQAAAAACAAIHVnkBCSgBAQECAgEAAAAFAQUWP20B',
        'CCgBAAAAAAAAAAAAAAADNpMEEhIAAAAAAQAAAAADAAUTUm8AEhIBAQAABAEAAAADAAUVSm0D',
        'D0wAAAAAAAAAAAAAAAAAAA6UIisAAAAAAAAAAAAAAAEGCCF/JjQAAAEAAAAAAAAAAAIFDyRn',
        'CjgAAAAAAAYAAAAAAAAAARuXIBkAAAAAAAAAAAABAAAEBjGILCAAAAAAAAIBAAAAAAALDDJk',
        'HzoAAAAAAAAAAAAAAAAAABaEIhcAAAAAAAAAAAAAAAAHDB6ILyIAAAAAAAAAAAAAAAAABheF',
        'FDUAAAAAAAAAAAAAAAAAAwySHRQAAAAAAQAAAAAAAAAFBh+OISYBAAABAQEAAAAAAAADEBJ5',
        'GTMAAAAAAAAAAAAAAAAAABWTJBkAAAAAAAAAAAAAAAADBxySIygAAAACAwEAAAAAAAADEido',
        'F0QAAAAAAAAAAAAAAAAAABGVIx4AAAAAAQAAAAAAAAALEBqKKCwAAAEDAAAAAAAAAAAOEyJk',
        'JS0AAAAAAAAAAAAAAAAAACN9HRkAAAAAAAAAAAACAAADBhOgJigAAAEDAgAAAAABAAAGChtz',
        'MSsFAgAAAAAAAAABAAAFB0BeJRYDAwAAAAAAAAAAAAAPDhCgIzQDAQMDAAAAAAAAAAMKEBh5',
        'FkEAAAAAAAAAAAAAAAAAABSNIhoAAAAAAAAAAAAAAAAFFBiKITIAAAACAQAAAAAAAAACCCRz',
        'D0YAAAAAAAAAAAAAAAAAAByHHh8AAAAAAAAAAAABAAEGCh6KJCsAAAAAAQAAAAAAAAAACSZ3',
        'Ez8AAAAAAAAAAAAAAAAAAUVvHxwAAAAAAAAAAAAAAAENEyKIHykAAAABAAAAAAAAAAABCDZ/',
        'GUIAAAAAAAAAAAAAAAAAACx4KBoAAAAAAAAAAAABAAELDhyHJCoAAAABAAAAAAAAAAABAyeE',
        'HRIAAAAAAAAAAAIHAAAKEimjHgQAAAAAAAACAgELAAETIS6LFQ4AAAAAAAAACgoVAB43JBw/',
        'DUMAAAAAAAAAAAAAAAAAAA6QJRgAAAAAAAAAAAAAAAEICxWHJyUAAAAAAAAAAAAAAAADBCR3',
        'CzwAAAAAAwAAAAAAAAATDQyIIhAAAAAAAQAAAAAAAAAGDi2JIC8BAAABAAAAAAAAAAADBSx5',
        'HzQAAAAAAAAAAAAAAAADBTN1IBMAAAAAAAAAAAAAAAADDS+RKCYAAAAAAAAAAAAAAAABCTB7',
        'HjwAAAAAAAAAAAAAEwcCARODIxQAAAAAAAAAAAABBx0ECg+TMSgAAAAAAAAAAAABABwHDw5z',
        'KU0BAAAAAAAAAAAAAAABBSFzRRkCAAAAAAAAAAAAAAABCC17LD0AAAAAAAAAAAABAAAGCSVz'
      ],
    },
    {
      name: '広',
      embeds: [
        'EgUAAAAAAQAAAAAAAAAACBelGgYAAAAAAQAAAAACAAAAERKXMwAAAAAAAAAAAAADAAADPBtL',
        'FQwAAAAAAAAAAAAAAAACExyhJAYAAAAAAAAAAAAAAAEIFiSGPgEAAAAAAAAAAAABAAcLIxpl',
        'GAwAAAAAAAAAAAAAAhM0IYMFKgQAAAAAAAEAAAAABQY1KYIAGwEAAAAACAYAAAABEQt5MCYA',
        'ERcBAAAAAAAAAAAAAAAADF2IJQUAAAAAAgAAAAAAAAMIEUuGJAIBAAAABAAAAAAAIBoQKD80',
        'DA4AAAAAAAAAAAAAAAABDnVmEggAAAAAAAAAAAAABAcLFE5zFgQAAAAAAAAAAAAAAAEBX1wt',
        'EBoAAAAAAAAAAAABAAAAHzaLIA4AAAAAAAAAAAAAAAAAHDeJOQkAAAAAAAAAAAAAAAABRjVN',
        'DQ0AAAAAAAAAAAAAAAAAAg2qGAkAAAAAAAAAAAAAAAAABCKMIQYAAAAAAAAAAAAAAAAAFjNj',
        'DQ0AAAAAAAAAAAAAAAAAAgyuFwkAAAAAAAAAAAAAAAAAByKNIwgAAAAAAAAAAAAAAAAAIDlT',
        'BwgAAAAADgAAAAAEAAABHhGhGgcAAAAACwAAAAABAAAAGBySMwIAAAABCQAAAAAAAAABPStM',
        'FBAAAAAAAAAAAAAAAAABCUaPJgcAAAAAAQAAAAAAAAIEB0mANAAAAAAAAgAAAAAAAAUEM0dK',
        'AAAAAAAAABANAQEAAAEwKoEZBQMAAAAAAAoIAgIFAAAtLo8HAAAAAAAAABUPAQgOAAFPYSkA',
        'EhICAAAAAAAAAAAAAAABDFCDIQIAAAAAAAAAAAAAAAEGB0qKNgAAAAAABAAAAAABAA0EL0w+',
        'EBcCAAAAAAAAAAAAAAAACl99IwUAAAAAAgAAAAAAAAMJFT+ENwEAAAAABAAAAAAAAA0GKExL',
        'GgQAAAAKAAAAAAAAAAAdCw6LKAQAAAAHAAAAAAAAAAAWBwuNLAEBAAEGAAAAAAAAAAAVCgyJ',
        'EAkAAAAAAAAAAAEBAAAABhGvFwUAAAAAAAAAAgECAAAUDg+QJAMAAAAAAAAAAwIDAAAYLxlS'
      ],
    },
    {
      name: '佑芽',
      embeds: [
        'aQgAAAAAAAAAAAAAAAABEl0wVAgAAAAAAAAAAAACAAABHS9lbgQAAAAAAAAAAAACAAAAGS1W',
        'bQIAAAAAAgAAAAACAAANNFsHYgAAAAAAAAAAAAACAAIGHi9cdAAAAAAAAgAAAAAFAAIMLiA+',
        'Sw0AAAAAAAAAAAADAAAAHWskMg8AAAAAAAAAAAEFAAACGC15NxYAAAAAAAAAAAANAAABChCT',
        'YwIAAAAAAAAAAAABAAACG2cdMgkAAAAAAQAAAAADAAAAIyaAQgMAAAACAQAAAAAEAAAGBENv',
        'cAUAAAAAAAAAAAAAAAAHKU8pTQ4AAAAAAAAAAAAAAAACEjZ4ZQMAAAAAAQMBAAADAAwTFDFJ',
        'gQAAAAAAAAAAAAAAAAAKHkkIZgIAAAAAAAAAAAABAAACFhtdTAIAAAAAAAIBAAAGAAIJChF8',
        'YwIAAAAAAAAAAAABAAAGI1kpVAsAAAAAAAAAAAAAAAADDyZ7cAQAAAAAAQAAAAABAAAGHzZA',
        'bQEAAAAAAQAAAAACAAAJN10FVQQAAAAAAAAAAAAEAAEEJDNafAQAAAAAAAAAAAABAAEILSI7',
        'hAEAAAAFAAAAAAABAAAkWBkFWQEBAAAHAAAAAAABAAAVNCxOWQEBAAANAAAAAAABAAATTSY3',
        'ZgEAAAAAAQAAAAABAAEPW0UHWgEAAAAAAAAAAAACAAMLMSNibQIAAAAAAQEAAAADAAMWMig7',
        'cwIAAAAAAgAAAAABAAcKWC0HZwAAAAAAAAAAAAADAAILKx1XewAAAAAAAwAAAAAEAAsOKhg5',
        'cgMAAAAAAgAAAAABAAgLVC4LZgAAAAAAAAAAAAAEAAIKKSBafAAAAAAAAwAAAAADAAoRJxs5',
        'cwIAAAAAAgAAAAACAAYKWykIaQAAAAAAAAAAAAACAAEKIylTeQAAAAAAAQEAAAAEAAcSJx44'
      ],
    },
    {
      name: '手毬',
      embeds: [
        'AAABCAIBNAIBAAEEAB6jHwUACgECAwQBFgIAAAEMABJmIRNGGAQAAAAACxIBAAACADBdIQs1',
        'BAAAAAAAMQcAAAQFAxemCw8TEwABAQAADwUAAQIZABtEExFoGgAAAAAADAkCAQA4AB9VCxQ0',
        'AgAAAAAAPAoAAAABCWBuDAYAEgEBAQAAJwUAAAACAD4+Fl4ADQAAAAAAHRIBAAEBIn4XFSQA',
        'AwAAAAAANBgAAAABAA2cJggEDgQAAQAAFRQAAAACAAtbHRBZFgEAAAAACzABAAACADBfDQYz',
        'AQAAAAMDMwgAAAEBABmZLwYJDwMBAAABHAYAAAACAB1CJw5nGQEAAgECDxUCAAACADJoFA8w',
        'BAAAAAAALg8AAAEBC3JWExAAFQEBAQAAGAoAAAACA0MrGHgAFQAAAAAADiAIAAAEJnceERwA',
        'AQAAAAAAOQgAAAABAAepHwgFEgEBAAAAHAYAAAADABVZExhMGAAAAAAAFwUBAQEBAAtXET41',
        'AgYCAAAANQQAAAAAAAadKRgJEQIBAAAAHgQAAAEEABBUIxNcGwAAAAAAEw4BAQEFACJiFhY8',
        'AAgAAAAALwQCAwEAAAGhKw0FBgIBAQAAGgQAAQQHAAZbGCNOHAAAAAAAFw0BAQECACBuDgk0',
        'AgEAAAAAIAUAAAABAJ0iCQAADQEBAAAADwMAAAACAF8fUAAAFAAAAAAACggBAQABAIYPNAAA',
        'AwAAAAAADxMCAQQFAASYVwsLGgIBAAAABgYCAQEFAAk+PiFkFwQAAAAAAQcHAQEcAB0/MSs6'
      ],
    },
    {
      name: '清夏',
      embeds: [
        'XgwAAAAAAAAAAQEGAAAAChxsNBMBAAAAAAAAAAIIAAAACCGIUgkAAAAAAAMAAAACAAACDyNu',
        'igAAAAAAAAAAAAAAAAAABBdEXwEBAAAAAAAAAAAAAAABBRNvdgAAAAAAAAAAAAAAAAAAECo5',
        'kw0AAAAAAAAAAAAAAAQBAxhCYhACAAAAAAAAAAAAAA0HCxZbdQYAAAAAAAAAAAAACAkCESs5',
        'hAIAAAAAAAAAAAAAACIJDVYAVQgBAQAAAAAAAAABDxQIGXEAaAQAAAAAAAEBAAABEg8ZLzcD',
        'cgYAAAAAAAAAAAAAAAABBghpRQYAAgAAAAAAAAACAAACDBh8ZQUAAAAAAAAAAAABAAAACx5d',
        'aQ8AAAAAAAAAAAAAAAgEAwdxMxIBAQAAAAAAAAAAAAYDCA6YUxUAAAAAAQAAAAAACAoHCCVN',
        'cxUAAAAAAAAAAA0WAAEIBQlWSwsAAAAAAAAAAAEOAAAKDhOHcAgAAAAAAAAABAYoAAkQCw07',
        'aBgAAAAAAAAAAAAAAAAAACtjOBwAAQAAAAAAAAACAAABCy58ZxoAAAAAAAAAAAAAAAAAB0FF',
        'eA8AAAAAAAAAAAAAAAABARBUTRYAAAAAAAAAAAAAAAAAAQ17hggAAAAAAAAAAAAAAAAFDCco',
        'dg0AAAAAAAAAAAAAAAAAAgNuPxEAAQAAAAAAAAABAAAACQuPPwgAAAAAAAAAAwMyAAAAACpN',
        'iwMAAAAAAAAAAAAAAAAAABlGWwQCAAAAAAAAAAAAAAACBRdvdAAAAAAAAAAAAAAAAAAAHCM7'
      ],
    },
    {
      name: 'リーリヤ',
      embeds: [
        'DgAAAAAAAAAAAAAKBAMCCCeWEgAAAAAAAAEAAAEHBgACDB2lHwAAAAAAAAABAAEMAwUFHDVW',
        'CQAAAAAAAAAAAAAhAAcBATOhEQAAAAAAAAIAAAEwAAADCi+IEgAAAAAAAAYGAgNOARQVIhg0',
        'CwAAAAAAAAEAAAALBgUnS4YAFQAAAAAAAAEBAQEIBgUdQJMAHAAAAAAACQQAAAEFHhgiQkEO',
        'AQAAAAAAAQEAAAAQAAAABzSiDgAAAAAAAgAAAAAIAAcGBS6UFgAAAAAABwMDAAEHABQSEzpP',
        'CwQAAAAAAAAAAAAGAAAAAB+gEgUAAAAAAAAAAAAEAAAAAhifGAsAAAEAAAABAAAIAAADEzlY',
        'CwAAAAAAAAAAAAALAAABCCeWDQAAAAAAAQEAAAAKAAABDCCWFQAAAAAAAAABAQAJAAAAEzZx',
        'BgAAAAAAAAAAAAELAAAABEacCgEAAAAAAAAAAAEOAAAAB2N0DwAAAAAAAAkEAQMOAAgaLVYl',
        'BgAAAAAAAAAGAAAEAAAAARqkCwAAAAAAAAEHAQADAAAABByaCwAAAAAAAAIQAQECAAYMCTVg'
      ],
    },
    {
      name: '星南',
      embeds: [
        'DxIAAAAAAAAAAAAAAAAAAAeaHAgAAAAAAAAAAAAAAAAAAQaXJgYAAAAAAAAAAQACAAECBgx9',
        'DggAAAAAAAABAAABAAABBAeaGgUAAAAAAAABAAEAAAABAgWULgQAAAAAAAAAAQACAAAABQV/',
        'Dg4AAAAAAAAAAAABAAAAAACkGAMAAAAAAAABAAAGAAABCAiOIQEAAAAAAAAAAAQLAAAABwt9',
        'DAwAAAAAAAABAAAAAAAAABKfGAYAAAAAAAABAQABAAAAAxGVGwYAAAAAAAABAAEDAAABGBR3',
        'DQAAAAAAAAAAAAAJAAAABAnBCgAAAAAAAAIDAQEZAAIIHB15CwAAAAAAAAMAAAEwAAYPLx1G',
        'DhoAAAAAAAAAAAAAABMBAQOXIQgAAAAAAAABAAEBAAcGCQmMLAYAAAAAAAAAAQACAgICCg2F'
      ],
    },
    {
      name: '千奈',
      embeds: [
        'agwAAAAAAAAAAAAAAAAFQilIYw8AAAAAAAAAAAAAAAAGPRZjWhQAAAAAAAAAAAAAAAAeLTw6',
        'JQ0AAAAAAAAAAAAAAAAYPSF8LwUAAAAAAAAAAAABAAAbGiOXRwIAAAAAAAAAAAAAABcsMTss',
        'HCQAAAAAAAAAAAABAAAKXxpoHigAAAAAAAAAAAABAAAFIiiWOCMAAAAAAAAAAAAAABseKiNK',
        'HAQCDwEAAAAACAICAAIagV0AHAUGEAEAAAAAAQIDAAESOTtyOAUAAwYBAwAAAAAAABpKHh1M'
      ],
    },
    {
      name: '美鈴',
      embeds: [
        'AQ8AAAAAAABLBAEAAAR4MAUlFAwAAAAAAAAWAgIEAAIjMBeMFhwAAAAAAAYLAgECAAAiR0NB',
        'AQwAAAAAAAA1AwICAABROglBGgMAAAAAAAAQAgEEAAAOLxCdIAAAAAAAAAAZAQEHAAAeKxt4',
        'BgAAAAAAAAA2KgUDADKODgQBPg4AAAAAAAAGDAYHAA4jKRFrSxoAAAAAAAAFAgMSAAATQCJN',
        'AQAAAAAAAABOAgICAAx2SwQADQMAAAAAAAAbAgEHAAAoPw97HgQHAgAAAAIIAAIBAAUgTB9c'
      ],
    },
    {
      name: '燕',
      embeds: [
        'BQsAAAAAAA8DAgEDAAdrbxwWHQkCAAAAAgECAQEDAAcaIUx8HwwAAAAAAgEEBAEDADErLiRU',
        'CgcAAAAAAAEJAQIJABFmWR8YHwcAAAAAAAABAQECAAMeFzaWEwwAAAAAAAACAgMCABAuRkg7',
        'CQAAAAAAAQkFAQEFLS9zJCEAHwEAAAAAAgIBAAABHSIdGJIADAAAAAABERADAAACQ2waDCQA',
        'BAAAAAAABQsAAAABACuYKA0CGQAAAAAABQIAAAABABUmFYwRDgAAAAABCAMAAAECAFsrITwO'
      ],
    },
    {
      name: '莉波',
      embeds: [
        'VgEAAAAAAAAAAAAGDSMcWUUANwcAAAAAAAAAAAAJDB0jK4oAPQMAAAAAAAEDAQESGxxGPDEC',
        'QQEAAAAAAAAAAAACAAABLm41IwkAAAAAAAAAAAADAAAALCiTLAMAAAAAAAICAAADAAMKOkpP',
        'RQIAAAAAAAEAAAAAABUKDk5MHgkCAwEAAAEBAAACAA8OChqfIQ0YBwAAAAAAAAAEAAAGFiKB',
        'VgEAAAAAAAAAAAABAAAAIlhNLQcAAAAAAAEAAAACAAABISidLgMAAAAAAAcBAQAFFAoMMkoz'
      ],
    },
    {
      name: '咲季',
      embeds: [
        'DgIAAAAAAAAAAABeAAALJWssGwAAAAAAAAAAAAAyAAAPKC6FHQEAAAAAAAABAQJOAwUrKC89',
        'DQQAAAAAAQAAAABQAAYHNWs6GAEAAQEAAAIDAQAuAAAtLyd3IwEAAAAAAAAAAABLAAcwMDM/'
      ],
    },
    {
      name: '撫子',
      embeds: [
        'FwAAAAAAAAABAQEjABYFCRmKDgAAAAAAAAAAAAIqAAAABiqaHQAAAAAAAAIAAAIZAAsdDSpq'
      ],
    },
    {
      name: '麻央',
      embeds: [
        'DAAAAAAABwEAAAAtAAACHDWDEgAAAAAAAAAAAAEsAAABH0ZyTgAAAAAAAQEAAAAFAAEEHjhn'
      ],
    }
      ]
